### ISSUE TITLE
Update to 1.20.2 and 1.20.6 would be amazing

### ISSUE THREAD

**Issue by morgantic** [poqbox/slotted-armor-hud#4]
Just letting you know there'd be a happy user if you could get this to 1.20.2 and 1.20.6, but please don't feel pressured to do so by his.

**Comment by poqbox** [comment]
You're not the only one :) The main reason why I stopped updating it past 1.20.1 is because of the changes made in 1.20.2. It changed how the hotbar is rendered, which is why the armor's HUD is bugged for those later versions. I'm relatively new to modding, and I have no idea how to work around it while making sure that it can still adapt to resource packs.

**Comment by poqbox** [comment]
Update, the mod has now been updated to 1.20.2-1.20.4. Not sure when 1.20.6 might be ready, but after the success of updating it to 1.20.2, I have a bit more motivation to get it working for 1.20.6.

**Comment by poqbox** [comment]
The mod has now been updated to 1.20.5-1.20.6 :)
